# Generated by Django 5.0.1 on 2024-04-20 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votacion.candidato', verbose_name='Candidato')),
            ],
        ),
    ]
